#!/usr/bin/env bash
#
# MIME Shield - TEST-ONLY PKI generator.
#
# !!! EVERYTHING GENERATED HERE IS FOR AUTOMATED TESTS ONLY !!!
# !!! The private keys are published in the repository and MUST NEVER be used for real mail. !!!
#
# Generates a throw-away test CA hierarchy and S/MIME certificates:
#   root CA -> intermediate CA -> end-entity certificates
#   alice      RSA-2048, alice@example.test     (sign + encrypt)
#   bob        RSA-3072, bob@example.test       (sign + encrypt)
#   carol      EC P-256, carol@example.test     (sign + key agreement)
#   mallory    RSA-2048, mallory@example.test   (valid, used for impersonation tests)
#   alice2     RSA-2048, alice@example.test     (second certificate for rotation tests)
#   expired    RSA-2048, expired@example.test   (2020-2021)
#   notyet     RSA-2048, notyet@example.test    (2035-2036)
#   wrongmail  RSA-2048, someone-else@example.test
#   server     RSA-2048, EKU serverAuth only    (bad purpose)
#   signonly   RSA-2048, KU digitalSignature only
#   legacyemail RSA-2048, e-mail only in subject emailAddress (no SAN)
#   evil       RSA-2048, SAN rfc822Name "victim@example.test, email:attacker@evil.test"
#   revoked    RSA-2048, revoked@example.test, listed on the intermediate's CRL
#   untrusted  RSA-2048, alice@example.test issued by an unrelated "rogue" CA
#   selfsigned RSA-2048, self-signed end entity for alice@example.test
# plus PKCS#12 variants (modern, legacy RC2/3DES, 3DES only, no key, mismatched key, EC, .pfx copy).
#
# Requires OpenSSL >= 3.4 (x509 -not_before/-not_after). Usage: generate.sh [outdir]
set -euo pipefail

OUT="${1:-$(cd "$(dirname "$0")" && pwd)/pki}"
PASS="test-password-Zażółć"   # non-ASCII on purpose (UTF-8)
mkdir -p "$OUT"
cd "$OUT"
rm -f ./*.pem ./*.crt ./*.key ./*.p12 ./*.pfx ./*.csr ./*.srl ./*.cnf ./*.der ./*.crl index.txt* crlnumber* serial* 2>/dev/null || true

cat > README.txt <<'EOF'
TEST-ONLY PKI generated by tests/fixtures/generate.sh.
These keys are PUBLIC (committed to the repository). NEVER use them for real e-mail.
PKCS#12 password: see PASS in generate.sh ("test-password-Zażółć").
EOF

cat > ext.cnf <<'EOF'
[ca_root]
basicConstraints = critical, CA:TRUE
keyUsage = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash

[ca_int]
basicConstraints = critical, CA:TRUE, pathlen:0
keyUsage = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always

[smime_rsa]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = emailProtection, clientAuth
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
subjectAltName = email:${ENV::SAN_EMAIL}
crlDistributionPoints = URI:http://crl.example.test/int.crl, URI:ldap://ldap.example.test/int
authorityInfoAccess = OCSP;URI:http://ocsp.example.test/, caIssuers;URI:http://ca.example.test/int.crt

[smime_ec]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyAgreement
extendedKeyUsage = emailProtection
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
subjectAltName = email:${ENV::SAN_EMAIL}

[server]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = email:${ENV::SAN_EMAIL}

[signonly]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature
extendedKeyUsage = emailProtection
subjectAltName = email:${ENV::SAN_EMAIL}

[legacyemail]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = emailProtection

[evil]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = emailProtection
subjectAltName = @evil_san

[evil_san]
# ONE rfc822Name whose value contains ", email:" - openssl_x509_parse() renders it ambiguously
email.1 = victim@example.test, email:attacker@evil.test

[selfsigned]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = emailProtection
subjectAltName = email:alice@example.test
EOF

export SAN_EMAIL=none@example.test
NB="$(date -u -d '-1 day' +%Y%m%d%H%M%SZ)"
NA="$(date -u -d '+3650 days' +%Y%m%d%H%M%SZ)"

# --- CAs ---
openssl req -new -x509 -newkey rsa:3072 -nodes -keyout root.key -out root.crt -sha256 -days 7300 \
  -subj "/C=PL/O=MIME Shield TEST ONLY/CN=MIME Shield Test Root CA" -extensions ca_root -config <(cat /etc/ssl/openssl.cnf ext.cnf) 2>/dev/null
openssl req -new -newkey rsa:3072 -nodes -keyout int.key -out int.csr -subj "/C=PL/O=MIME Shield TEST ONLY/CN=MIME Shield Test Intermediate CA" 2>/dev/null
openssl x509 -req -in int.csr -CA root.crt -CAkey root.key -CAcreateserial -out int.crt -sha256 -days 5000 -extfile ext.cnf -extensions ca_int 2>/dev/null
openssl req -new -x509 -newkey rsa:2048 -nodes -keyout rogue.key -out rogue.crt -sha256 -days 7300 \
  -subj "/C=PL/O=Rogue TEST ONLY/CN=Rogue Test CA" -extensions ca_root -config <(cat /etc/ssl/openssl.cnf ext.cnf) 2>/dev/null
cat int.crt root.crt > chain.pem

issue() { # name email keyspec ext ca_cert ca_key [not_before not_after] [subject]
  local name=$1 email=$2 keyspec=$3 ext=$4 cacrt=$5 cakey=$6 nb=${7:-$NB} na=${8:-$NA} subj=${9:-"/C=PL/O=MIME Shield TEST ONLY/CN=$1 (TEST ONLY)"}
  export SAN_EMAIL="$email"
  if [[ $keyspec == ec ]]; then
    openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out "$name.key" 2>/dev/null
  else
    openssl genpkey -algorithm RSA -pkeyopt "rsa_keygen_bits:$keyspec" -out "$name.key" 2>/dev/null
  fi
  openssl req -new -key "$name.key" -out "$name.csr" -subj "$subj" 2>/dev/null
  openssl x509 -req -in "$name.csr" -CA "$cacrt" -CAkey "$cakey" -CAcreateserial -out "$name.crt" -sha256 \
    -not_before "$nb" -not_after "$na" -extfile ext.cnf -extensions "$ext" 2>/dev/null
  rm -f "$name.csr"
}

issue alice     alice@example.test    2048 smime_rsa int.crt int.key
issue bob       bob@example.test      3072 smime_rsa int.crt int.key
issue carol     carol@example.test    ec   smime_ec  int.crt int.key
issue mallory   mallory@example.test  2048 smime_rsa int.crt int.key
issue alice2    alice@example.test    2048 smime_rsa int.crt int.key
issue expired   expired@example.test  2048 smime_rsa int.crt int.key 20200101000000Z 20210101000000Z
issue notyet    notyet@example.test   2048 smime_rsa int.crt int.key 20350101000000Z 20360101000000Z
issue wrongmail someone-else@example.test 2048 smime_rsa int.crt int.key
issue server    server@example.test   2048 server    int.crt int.key
issue signonly  signonly@example.test 2048 signonly  int.crt int.key
issue legacyemail legacy@example.test 2048 legacyemail int.crt int.key "$NB" "$NA" "/C=PL/O=MIME Shield TEST ONLY/CN=legacyemail (TEST ONLY)/emailAddress=legacy@example.test"
issue evil      victim@example.test   2048 evil      int.crt int.key
issue revoked   revoked@example.test  2048 smime_rsa int.crt int.key
issue untrusted alice@example.test    2048 smime_rsa rogue.crt rogue.key
# self-signed end entity
openssl req -new -x509 -newkey rsa:2048 -nodes -keyout selfsigned.key -out selfsigned.crt -sha256 -days 3650 \
  -subj "/CN=selfsigned alice (TEST ONLY)" -extensions selfsigned -config <(cat /etc/ssl/openssl.cnf ext.cnf) 2>/dev/null

# --- CRL of the intermediate (revokes "revoked") ---
mkdir -p ca && : > ca/index.txt && echo 1000 > ca/crlnumber
cat > ca.cnf <<EOF
[ ca ]
default_ca = int
[ int ]
database = $OUT/ca/index.txt
crlnumber = $OUT/ca/crlnumber
certificate = $OUT/int.crt
private_key = $OUT/int.key
default_md = sha256
default_crl_days = 3650
EOF
openssl ca -config ca.cnf -revoke revoked.crt -crl_reason keyCompromise -batch 2>/dev/null
openssl ca -config ca.cnf -gencrl -out int.crl.pem -batch 2>/dev/null
openssl crl -in int.crl.pem -outform DER -out int.crl
# an "empty" CRL for the root (nothing revoked)
mkdir -p caroot && : > caroot/index.txt && echo 2000 > caroot/crlnumber
sed -e "s#$OUT/ca/#$OUT/caroot/#g" -e "s#int.crt#root.crt#" -e "s#int.key#root.key#" ca.cnf > caroot.cnf
openssl ca -config caroot.cnf -gencrl -out root.crl.pem -batch 2>/dev/null
openssl crl -in root.crl.pem -outform DER -out root.crl
rm -rf ca caroot ca.cnf caroot.cnf

# --- PKCS#12 ---
p12() { # name outfile [extra args...]
  local name=$1 out=$2; shift 2
  openssl pkcs12 -export -inkey "$name.key" -in "$name.crt" -certfile int.crt -name "$name TEST ONLY" \
    -passout "pass:$PASS" -out "$out" "$@" 2>/dev/null
}
for n in alice bob carol mallory alice2 expired notyet wrongmail server signonly legacyemail evil revoked untrusted; do
  p12 "$n" "$n.p12"
done
cp alice.p12 alice.pfx
p12 alice alice-legacy.p12 -legacy
p12 alice alice-3des.p12 -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES -macalg sha1
openssl pkcs12 -export -nokeys -in alice.crt -certfile int.crt -passout "pass:$PASS" -out alice-nokey.p12 2>/dev/null
# certificate + non-matching key (OpenSSL refuses to build such a PKCS#12, so a PEM bundle is used)
cat alice.crt bob.key > mismatch.pem
openssl pkcs12 -export -inkey selfsigned.key -in selfsigned.crt -passout "pass:$PASS" -out selfsigned.p12 2>/dev/null
openssl pkcs12 -export -inkey alice.key -in alice.crt -certfile int.crt -passout "pass:" -out alice-nopass.p12 2>/dev/null

# PEM bundles with certificate + key (for PEM import)
cat alice.crt alice.key int.crt > alice-bundle.pem
openssl pkey -in alice.key -aes256 -passout "pass:$PASS" -out alice-enc.key 2>/dev/null
cat alice.crt alice-enc.key int.crt > alice-bundle-enc.pem
openssl x509 -in bob.crt -outform DER -out bob.der

rm -f int.csr ./*.srl
chmod 0644 ./*
echo "TEST PKI generated in $OUT"
